version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "wandera/delta"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "wandera/delta"

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - "wandera/delta"

